markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: 
title: ZhangXin's Blog
description: Java, C, C++, Linux, MySQL, Backend ...
email: xin_zhang23#126.com
github: zhangxin23

config:
  js_dir:
  img_dir:
  css_dir:
